config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "pages/home", to: "pages#home"
#Below, we add all resources for recipes, but also make it a do block so that we create a nested route
#in order to add a route to create comments within the Recipe route. "/recipe/ID/comment"
  resources :recipes do
    resources :comments, only: [:create]
  end
#Below, we set up the normal routes for chefs, but we exclude the :new route, and in place, set up a route manually to
#act as the new route. Telling it the verb is GET, the prefix "/signup" and the action 'chefs#new'
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :ingredients, except: [:destroy]
#Below is the route this communication will go through.
  mount ActionCable.server => '/cable'
#Below, we create the routes for the Chatroom, to our chatrooms controller's show action.
  get '/chat', to: 'chatrooms#show'
#Below, we create a route path for new massges to be created
  resources :messages, only: [:create]
end 










app/models/recipe.rb
class Recipe < ApplicationRecord
  default_scope -> { order(updated_at: :desc)}
  validates :name, presence: true
  validates :description, presence: true, length: {minimum: 5, maximum: 500}
  validates :chef_id, presence: true 
  #Below shows recipes sorted by date in descending order
  #Below, sets up association between ingredients and recipe_ingredients
  belongs_to :chef #this is singular because it is the ONE side of the MANY side
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
#Below, sets up one to many association between Comments, and if a recipe is destroyed, so are the comments
  has_many :comments, dependent: :destroy 
  has_rich_text :description
  # has_one_attached :image
end 

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
#Below, before_action runs first everytime an action is called. Here we run "set_recipe" method defined in 
#the Private section to find and set_recipe solely for the actions listed after "only:" in square brackets [] 
before_action :set_recipe, only: [:show, :edit, :update, :destroy]
#Below, we're calling "require_user" from "application_controller" to allow visitors only to see Index and Show
before_action :require_user, except: [:index, :show]
#Below, restricts only the usre who created the recipe to edit, update, or destroy it.
before_action :require_same_user, only: [:edit, :update, :destroy]
  def index #Below we allow pagination to Recipe's all and set it to 5 per page
    @recipes = Recipe.paginate(page: params[:page], per_page: 5)

  end 
  
  def show
    @comments = @recipe.comments.paginate(page: params[:page], per_page: 5)
    
    @comment = Comment.new #This allows new comments within /recipe/show.html.erb 
  end 
  
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(recipe_params) #recipe_params is the method defined under "private"
    @recipe.chef = current_chef #Recipe will be created by the current logged in Chef.
    if @recipe.save #If it saves, display Flash message success, if not move to 'else'
      flash[:success] = "Recipe was created successfully!" #Shows a Flash message of success
      redirect_to recipe_path(@recipe) #Redirects to the Show recipe path page
    else
      render 'new' #Reload the New template with errors
    end 
  end
  
  def edit
    
  end 
  
  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Recipe was updated successfully!"
      redirect_to recipe_path(@recipe)
    else 
      render 'edit'
    end 
  end 
  
  def destroy
    Recipe.find(params[:id]).destroy
    flash[:success] = "Recipe deleted successfully!"
    redirect_to recipes_path
  end
  
  private
  
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end
  
  def recipe_params #Whitelisting what we pass in: the name, description, and now ingredients' IDs 
    params.require(:recipe).permit(:name, :description, ingredient_ids: [] )
  end
#Now, we build a method to allow only the user who created the associated recipe to be able to modify it.
  def require_same_user
#Below, the if statement is if the logged in chef is not equal to the recipe's associated chef owner, then you get 
#a error flash message and redirected to the recipes show page. We also add if the logged in user is NOT an admin.
    if current_chef != @recipe.chef and !current_chef.admin?
      flash[:danger] = "You can only modify your own recipes!"
      redirect_to recipes_path
    end
  end
  
end 

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>
<!--  The above renders the standard error display, but also includes an obj: method, telling our _errors
.html.erb partial that when this partial is rendered, it's for the instance variable of @recipe. Since "obj"
is a variable to hold instance variables, it can be named whatever you wish.-->
<div class="row">
  <div class="col-md-12">
    <%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"}) do
    |f| %>
    <div class="form-group">
      <div class="control-label col-md-2">
        <%= f.label :name %>
        <!-- "f" being the do block iterator, and ":name" being our recipe's name attribute  -->
      </div>
      <div class="col-md-8">
        <%= f.text_field :name, class: "form-control", placeholder: "Name of recipe", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-md-2">
        <%= f.label :description %>
      </div> 
      <div class="col-md-8 field">
        <%= f.rich_text_area :description, class: "form-control", placeholder: "Enter steps of Recipe" %>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-md-offset-2 col-md-8">
          <!--  Below, to show all the ingredients we have, we must loop through them -->
          <!-- So we're looping a display of check boxes, which are the "ingredient_ids". Then list all ingredients, 
specified by their attributes of the table, :id and :name. -->
          <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id,
          :name do |cb| %> <% cb.label(class: "checkbox-inline input_checkbox")
          cb.check_box(class: "checkbox") + cb.text %> <% end %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <%= f.submit class: "btn btn-primary btn-lg btn-xlarge" %>
        <!-- class "btn-xlarge makes it green -->
      </div>
    </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request and return to Recipes Listing", recipes_path
      %> ]
    </div>
  </div>
</div>
<!-- Below - JS Code to disable attachments on trix editor description form input-->
<script> 
$( document ).ready(function() {
   $("span.trix-button-group--file-tools").remove();
});
 
</script>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
  <div class="row">
     <div class="col-md-2" >
       <section class="chef_info center">
         <%= gravatar_for(recipe.chef, size: 120) %>
       </section>
     </div>
     <div class="col-md-8 well">
       <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
       <p><%= recipe.description.to_plain_text.truncate(150) %></p>
<!--  Below, we check if there are ingredients inside the recipe and display them if so -->
        <%  if recipe.ingredients.any? %>
<!-- Below, we use magic to tell Rails to Render a "ingredients" partial instead of using an iterator here-->        
          <p>Ingredients: <%= render recipe.ingredients  %> </p>
        <% end %>
       <p>
         <span class="quiet"><small>Created <%= time_ago_in_words(recipe.created_at) %> ago, by <%= recipe.chef.chefname.capitalize %>
                                              | <%= pluralize(recipe.comments.count, 'Comment')%> </small></span>
       </p>
<!--  Below we check if the user is logged in as chef belonging to recipes or if it's an admin allowing modification -->
     <% if logged_in? && (current_chef == recipe.chef || current_chef.admin?) %>
       <div class="recipe-actions">
        <%= link_to 'Edit this Recipe', edit_recipe_path(recipe), class: "btn btn-xs btn-warning" %>
        <%= link_to "Delete this Recipe", recipe_path(recipe), method: :delete, 
                                      data: { confirm: 'Are you sure you want to delete this recipe?' }, 
                                      class: "btn btn-xs btn-danger" %>
       </div>
     <% end %>
     </div>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: 'Edit an existing recipe' %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "Listing all Recipes" %>
<div align="center">
  <%= will_paginate %>
</div>
<%= render 'recipe', obj: @recipes %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: 'Create a new recipe' %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>
<!--  Here we render the partial, "shared/page_title" because it's in a separate folder. Then,
after the location, we define what the "title" variable means that we set in our partial, and 
in the Show page's case, it is the display of the Recipe's name, so @recipe.name-->
<div class="well col-md-8 col-md-offset-2">
  <h4 class="center description"><strong>Steps: </strong></h4>
  <hr />
  <%= @recipe.description %> <!-- Displays description as multi-line format--> 
  <hr />
<!--  Below displays if there are any ingredients associated with the recipe -->
  <% if @recipe.ingredients.any? %>
    <p><b>Ingredients: </b><%= render @recipe.ingredients %></p>
  <% end %>
  <div class="pull-right">
    <p class="center">
      <em>Created by:</em>
    </p>
    <p class="center">
      <%= link_to gravatar_for(@recipe.chef), chef_path(@recipe.chef) %>
    </p>
    <p class="center">
      <small><%= @recipe.chef.chefname.capitalize %></small>
      <div class="pull-right"><%= time_ago_in_words(@recipe.created_at) %> ago</div>
    </p>
  </div>
  <div class="recipe-actions">
<!--  Below will determine whether to show "Edit & Delete" if the person is logged in AND if that logged in user is the 
chef associated with that recipe. Or if the user is admin. -->
    <% if logged_in? && (current_chef == @recipe.chef || current_chef.admin?) %>
    <%= link_to 'Edit this Recipe', edit_recipe_path(@recipe), class: "btn btn-xs btn-warning" %>
    <%= link_to "Delete this Recipe", recipe_path(@recipe), method: :delete, 
                                      data: { confirm: 'Are you sure you want to delete this recipe?' }, 
                                      class: "btn btn-xs btn-danger" %>
    <% end %>
  </div>
</div>
<div class="col-md-4 col-md-offset-4 colormatch center">
   <%= link_to "Return to Recipe's Listing", recipes_path, class: "btn btn-success btn-primary" %> 
</div>

<!--  Below is the form for adding NEW comments to the Recipe show page -->
<% if logged_in? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Comments: </h3>
      <hr />
<!-- Below, we need to provide both recipe variable and @comment instance variable for form_for helper, because of
the nested route in "routes.rb" and the @comment instance variable needs to be defined in recipes_controller.rb. 
Below, adding "remote: true" allows the form to be submitted via AJAX-->
     <%= form_for([@recipe, @comment], remote: true, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :description, "Comment" %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :description, rows: 8, class: "form-control", placeholder: "Enter Comment Here" %>
        </div>
      </div>  
        <div class="form-group">
          <div class="col-md-offset-2 col-md-10">
            <%= f.submit "Submit Comment", class: "btn btn-primary btn-lg btn-xlarge" %> <!-- class "btn-xlarge makes it green -->
          </div>
        </div>
      <% end %>
        <hr />
      </div>
    </div>
<% end %>

<!-- Below displays comments on Recipe page if there are any assigned to the @recipe -->
<% if @recipe.comments != 0 %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Prior Comments: </h3>
<!--  Below, we use this id "messages" to set up a JS event listener, anytime something happens here,
JS will then react and execute code. This occurs in "/assests/javascripts/channels/comments.coffee" under "received -->
      <div id="messages"> 
<!--  Below, we use a different method of rendering a partial. After "partial:" we put the folder path and then
partial name in single ''s and then we have to specify an object as the instance variable, which is @comments. We 
have to grab this instance variable from the recipes_controller.rb for it to render properly. Since this is the Show
page, we have to specify this instance variable inside the controller's "show" action. -->
        <%= render partial: 'comments/comments', object: @comments %>
      </div>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>No Comments!</h3>
    </div>
  </div>
<% end %>

