config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "pages/home", to: "pages#home"
#Below, we add all resources for recipes, but also make it a do block so that we create a nested route
#in order to add a route to create comments within the Recipe route. "/recipe/ID/comment"
  resources :recipes do
    resources :comments, only: [:create]
  end
#Below, we set up the normal routes for chefs, but we exclude the :new route, and in place, set up a route manually to
#act as the new route. Telling it the verb is GET, the prefix "/signup" and the action 'chefs#new'
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :ingredients, except: [:destroy]
#Below is the route this communication will go through.
  mount ActionCable.server => '/cable'
#Below, we create the routes for the Chatroom, to our chatrooms controller's show action.
  get '/chat', to: 'chatrooms#show'
#Below, we create a route path for new massges to be created
  resources :messages, only: [:create]
end 










app/views/layouts/_admin.html.erb
<h1>
  <span>
    ADMIN!
  </span>
</h1>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <hr />
    <small>
      Copyright &copy; My Recipes</a>
      by <a href="http://www.facebook.com/visceralcomputers">Benjamin Broestl</a>
    </small>
        <a class="pull-right" href="/about">About</a>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
       <div class="alert alert-<%= name %>"> <!-- This name will be filled in by the attribute flash[] like :success-->
         <a href="#" class="close" data-dismiss="alert">&#215;</a> <!-- Shows the X Close button -->
         <%= msg %>
       </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "MyRecipes", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
<!--  Below is Chefs and All Recipes Links for non-logged in users -->        
        <li><%= link_to "Chefs", chefs_path %></li>
        <li><%= link_to "All Recipes", recipes_path %></li>
<!--  Below is Recipes dropdown in If Condition & Chatroom -->
        <% if logged_in? %>
          <li><%= link_to "Chatroom", chat_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Recipes <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Create a new Recipe", new_recipe_path %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <% end %>
<!--  Below is Ingredients dropdown for no-logged in users-->
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ingredients <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Ingredients", ingredients_path %></li>
<!--  Below, we create a loop in the dropdown to display every ingredient -->
            <% Ingredient.all.each do |ingredient| %>
              <li><%= link_to ingredient.name.capitalize, ingredient_path(ingredient) %></li>
            <% end %>
            <li role="separator" class="divider"></li>
            <% if logged_in? && current_chef.admin? %>
            <li><%= link_to "New Ingredient", new_ingredient_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      
      <ul class="nav navbar-nav navbar-right">
<!--  BElow, we have the Dropdown menu appear in navbar only if the user is logged in -->
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_chef.chefname.capitalize %>'s Profile<%= " - Admin" if current_chef.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
<!-- Below, we display the profile link with a link to the current_chef profile when logged in due to above "if"-->
              <li><%= link_to "View your profile", chef_path(current_chef) %></li>
              <li><%= link_to "Edit your profile", edit_chef_path(current_chef) %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", login_path  %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrecipes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %> <!-- Shows our FLash message partial -->
    <div class="container">
      <%= yield %>
    </div> 
    <%= render 'layouts/footer' %>
  </body>
</html> 